name = "nextjs-cloudflare-starter-preview"
compatibility_date = "2024-05-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_ON_PAGES = "1"

[[d1_databases]]
binding = "DB"
database_name = "nextjs-cloudflare-starter-db"
# Replace with the database ID from `wrangler d1 create`
database_id = "00000000-0000-0000-0000-000000000000"

[[r2_buckets]]
binding = "R2"
# Replace with the bucket name created via `wrangler r2 bucket create`
bucket_name = "nextjs-cloudflare-starter-assets"
