name = "nextjs-cloudflare-starter"
compatibility_date = "2024-05-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_ON_PAGES = "1"

[[d1_databases]]
binding = "DB"
database_name = "nextjs-cloudflare-starter-db"
database_id = "057a06ef-544d-4ab3-b464-9288c72c0831"

[[r2_buckets]]
binding = "R2"
bucket_name = "nextjs-cloudflare-starter-assets"
