name = "nextjs-cloudflare-starter"
main = ".open-next/worker/index.mjs"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/static"
binding = "ASSETS"

[vars]
NEXT_RUNTIME = "nodejs"

[[d1_databases]]
binding = "DB"
database_name = "nextjs-cloudflare-starter"
database_id = "00000000-0000-0000-0000-000000000000"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "nextjs-cloudflare-starter-assets"
